[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.27"
etcd-client = "0.14"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"